#!/bin/bash

#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot -1 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 32 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 16 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 8 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 4 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 2 &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 1000  --lr 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot 1 &
#wait


#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0001 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0002 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0005 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0010 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0020 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0050 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr 0.0100 --comment DEBUG_adjustLR  --num_shot -1  --pooling_strategy learnablePrompt &
#wait

#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.0002 --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.0005 --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001  --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.002  --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.005  --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.010  --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.020  --lr_IB 0.005 --comment DEBUG_adjustLR_TB_IB  --num_shot -1  --pooling_strategy learnablePrompt &
#wait

#
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.01     --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one &
##python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one &
##python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.0001  --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.00001  --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.000001 --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one &
#wait


#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one --bagLevel_n_ctx 16 --csc False &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one --bagLevel_n_ctx 32 --csc True &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one --bagLevel_n_ctx 8  --csc True &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one --bagLevel_n_ctx 32 --csc False &
#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment DEBUG  --num_shot -1  --pooling_strategy first-one --bagLevel_n_ctx 8  --csc False &
#wait


#python -u train_CAMELYONFeat_MIL_CLIP.py --epochs 500  --lr_TB 0.001   --lr_IB 0.001 --comment BASELINE_LinearProbeABMIL  --num_shot -1  --pooling_strategy NoCoOp

#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.3  --NegBagBreakProP 0.7 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.3  --NegBagBreakProP 0.5 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.3  --NegBagBreakProP 0.3 &
#
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.5  --NegBagBreakProP 0.7 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.5  --NegBagBreakProP 0.5 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.5  --NegBagBreakProP 0.3 &
#
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.7  --NegBagBreakProP 0.7 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.7  --NegBagBreakProP 0.5 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment DEBUG_NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.7  --NegBagBreakProP 0.3 &
#wait

#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0.0   &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0.001 &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0.01  &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0.1   &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 1.0   &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 100   &
#python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.5 --p_bag_drop_out 0.5 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 1000  &
#wait

# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 50    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.005 --lr_IB 0.005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 75    &
# wait
# 
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.0005 --lr_IB 0.0005 --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.001  --lr_IB 0.001  --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.002  --lr_IB 0.002  --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
# python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500  --lr_TB 0.010  --lr_IB 0.010  --comment NewInitBagPromptCtx_26head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 10    &
# wait


##### EXP with only 1 head ########
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 8   --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 4   --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 2   --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 1   --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# 
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot -1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 8   --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 4   --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 2   --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 1000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_1head  --num_shot 1   --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 0 &   
# wait
##### EXP with only 1 head : results show 1 head not comparable to 26 head ########


##### EXP with multiple seed at 16-shot ########
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 1 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 2 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 3 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 4 &   
# wait

# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 5 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 6 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 7 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 8 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 2000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 16  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 9 &   
# wait

##### EXP with multiple seed at 16-shot: Seed 0 and 9 get good resutls ########


##### EXP with multiple seed at 8-shot ########
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 6000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 8  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 6 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 6000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 8  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 7 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 6000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 8  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 8 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 6000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 8  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 9 &   
# wait

##### EXP with multiple seed at 4-shot ########
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 1 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 2 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 3 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 4 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 5 &   
# wait
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 6 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 7 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 8 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 9 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 10 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.0 --p_bag_drop_out 0.0 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 11 &   
# wait

# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 16 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 17 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 18 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 19 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 20 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 4  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 21 &   
# wait
# 
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 16 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 17 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 18 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 19 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 20 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 8000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 2  --pooling_strategy learnablePrompt_multi --p_drop_out 0.4 --p_bag_drop_out 0.4 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 21 &   
# wait

# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 16 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 17 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.002 --lr_IB 0.002 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 18 &   
# wait

# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.02 --lr_IB 0.02 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 26 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.02 --lr_IB 0.02 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 27 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 20000  --lr_TB 0.02 --lr_IB 0.02 --comment NewInitBagPromptCtx_26head  --num_shot 1  --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --NegBagBreakProb 0.0  --NegBagBreakProP 1.0 --weight_lossA 25  --seed 28 &   
# wait


# Ablation on CoOp+ABMIL
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 0 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 1 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 2 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 3 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 4 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 0 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 1 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 2 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 3 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 4 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 0 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 1 &   
# wait
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 2 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 3 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 4 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 0 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 1 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 2 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 3 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 4 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 0 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 1 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 2 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 3 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 4 &   
# wait
# 
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 10 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 11 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 12 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 13 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 14 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 10 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 11 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 12 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 13 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 14 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 10 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 11 &   
# wait
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 12 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 13 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 14 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 10 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 11 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 12 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 13 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 14 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 10 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 11 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 12 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 13 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 14 &   
# wait
# 
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 20 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 21 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 22 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 23 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 16 --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 24 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 20 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 21 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 22 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 23 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 8  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 24 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 20 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 21 &   
# wait
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 22 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 23 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 4  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 24 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 20 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 21 &   
# CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 22 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 23 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 2  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 24 &   
# CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 20 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 21 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 22 &   
# CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 23 &   
# CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_ABMIL  --num_shot 1  --pooling_strategy ABMIL --p_drop_out 0.2 --p_bag_drop_out 0.2  --seed 24 &   
# wait

# Ablation on CoOp+Instance Prompt
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 0 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 1 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 2 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 3 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 4 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 5 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 6 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 7 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 8 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 9 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 10 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 11 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 12 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 13 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 14 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 15 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 16 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 17 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 18 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 16 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 19 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 0 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 1 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 2 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 3 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 4 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 5 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 6 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 7 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 8 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 9 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 10 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 11 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 12 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 13 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 14 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 15 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 16 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 17 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 18 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 8 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 19 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 0 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 1 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 2 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 3 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 4 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 5 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 6 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 7 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 8 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 9 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 10 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 11 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 12 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 13 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 14 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 15 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 16 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 17 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 18 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 4 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 19 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 0 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 1 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 2 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 3 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 4 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 5 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 6 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 7 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 8 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 9 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 10 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 11 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 12 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 13 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 14 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 15 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 16 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 17 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 18 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 2 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 19 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 0 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 1 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 2 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 3 &   
wait
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 4 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 5 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 6 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 7 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 8 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 9 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 10 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 11 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 12 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 13 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 14 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 15 &   
CUDA_VISIBLE_DEVICES=0 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 16 &   
CUDA_VISIBLE_DEVICES=1 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 17 &   
CUDA_VISIBLE_DEVICES=2 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 18 &   
CUDA_VISIBLE_DEVICES=3 python -u train_CAMELYONFeat_MIL_CLIP.py  --epochs 500 --lr_TB 0.02 --lr_IB 0.02 --comment Ablation_CoOp_InstancePrompt --num_shot 1 --pooling_strategy learnablePrompt_multi --p_drop_out 0.2 --p_bag_drop_out 0.2 --weight_lossA 25  --seed 19 &   
wait
